steps:
- name: gcr.io/cloud-builders/gcloud
  entrypoint: bash
  args: 
    - -cx
    - |
        gcloud functions deploy upvote \
          --runtime python311 \
          --entry-point upvote \
          --set-env-vars instance=vote-instance,database=votes
